### ISSUE TITLE
Error: Cannot parse content. No Content-Type defined.

### ISSUE THREAD

**Issue by LizanLycan** [svix/svix-webhooks#1312]
### Version
1.22.0

* 1.22.0
### Platform

Darwin MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64

### Description

I tried this code:

```
svixClient.eventType.list({ includeArchived: true })
```

I expected to see this happen: 
* Listing me the event types.

Instead, this happened: 
```
Error: Cannot parse content. No Content-Type defined.
    at Function.parse (/Users/user/Documents/project/node_modules/.pnpm/svix@1.22.0/node_modules/svix/src/openapi/models/ObjectSerializer.ts:602:19)
    at EventTypeApiResponseProcessor.<anonymous> (/Users/user/Documents/project/node_modules/.pnpm/svix@1.22.0/node_modules/svix/src/openapi/apis/EventTypeApi.ts:1208:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Documents/project/node_modules/.pnpm/svix@1.22.0/node_modules/svix/dist/openapi/apis/EventTypeApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```

**Comment by tasn** [comment]
The libraries return this when the server returns a malformed response. Which server are you working against?

**Comment by tasn** [comment]
Closing this as no response (+ libraries have changed significantly since).
