### ISSUE TITLE
Don't get any good error response 

### ISSUE THREAD

**Issue by kristianbendren** [svix/svix-webhooks#1432]
### Version

Svix API (1.4)

### Platform

C# nuget and svix running on self hosted Docker 

### Description

Send an update request on Endpoint and got this. Entered all the values in the request body.

System.Exception: Error with response: Svix.Client.ApiException: Error calling V1EndpointUpdate:
System.Exception
Error with response: Svix.Client.ApiException: Error calling V1EndpointUpdate: 
   at Svix.Api.EndpointApi.V1EndpointUpdateWithHttpInfoAsync(String appId, String endpointId, EndpointUpdate endpointUpdate, CancellationToken cancellationToken)
   at Svix.Api.EndpointApi.V1EndpointUpdateAsync(String appId, String endpointId, EndpointUpdate endpointUpdate, CancellationToken cancellationToken)
   at Svix.Endpoint.UpdateAsync(String appId, String endpointId, EndpointUpdate endpoint, String idempotencyKey, CancellationToken cancellationToken)

**Comment by tasn** [comment]
@svix-jplatte is working on new versions of the libs that will make these much better.

**Comment by svix-jplatte** [comment]
Closing this as we rewrote the C# lib a couple months ago, let us know if there are still issues and we can reopen.
