### ISSUE TITLE
Better error messages (python sdk)

### ISSUE THREAD

**Issue by blakew** [svix/svix-webhooks#1459]
### Motivation

It's difficult to debug error messages using the python sdk

ex:

```
>>> endpoint_out = await svix.endpoint.create(appid,EndpointIn(**svix_endpoint_args,secret=secret))
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/__main__.py", line 58, in runcode
    return future.result()
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/Users/blakewillmarth/faraday/fdy/workers/model_train/.venv/lib/python3.10/site-packages/svix/api.py", line 464, in create
    return await v1_endpoint_create.request_asyncio(
  File "/Users/blakewillmarth/faraday/fdy/workers/model_train/.venv/lib/python3.10/site-packages/svix/internal/openapi_client/api/endpoint/v1_endpoint_create.py", line 240, in request_asyncio
    await request_asyncio_detailed(
  File "/Users/blakewillmarth/faraday/fdy/workers/model_train/.venv/lib/python3.10/site-packages/svix/internal/openapi_client/api/endpoint/v1_endpoint_create.py", line 210, in request_asyncio_detailed
    return _build_response(client=client, response=response)
  File "/Users/blakewillmarth/faraday/fdy/workers/model_train/.venv/lib/python3.10/site-packages/svix/internal/openapi_client/api/endpoint/v1_endpoint_create.py", line 73, in _build_response
    parsed=_parse_response(client=client, response=response),
  File "/Users/blakewillmarth/faraday/fdy/workers/model_train/.venv/lib/python3.10/site-packages/svix/internal/openapi_client/api/endpoint/v1_endpoint_create.py", line 62, in _parse_response
    raise HTTPValidationError.init_exception(response.json(), response.status_code)
svix.internal.openapi_client.models.http_validation_error.HTTPValidationError
```

### Proposal

It would be nice to get detail about the validation error in the error message.

**Comment by tasn** [comment]
I'm with you, thanks for reporting!

**Comment by tasn** [comment]
Btw, @svix-jplatte is working on new versions of the libs that will make these much better.

**Comment by tasn** [comment]
The new versions are out, and I believe this should be fixed! If that's not the case, let us know and we'll take a look.
