### ISSUE TITLE
Get or create application is not idempotent

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#427]
## Bug Report
Get or create application does not seem idempotent. The second call crashes with a 409 conflict error.

```python
>>> application_out = svix.application.get_or_create(ApplicationIn(
...      uid="unique-app-identifier",
...      name="My first application",
...      rate_limit=1000
...  ))
>>> application_out = svix.application.get_or_create(ApplicationIn(
...      uid="unique-app-identifier",
...      name="My first application",
...      rate_limit=1000
...  ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex.rejto/.pyenv/versions/aurelia/lib/python3.9/site-packages/svix/api.py", line 235, in get_or_create
    return create_application_api_v1_app_post.sync(
  File "/Users/alex.rejto/.pyenv/versions/aurelia/lib/python3.9/site-packages/svix/internal/openapi_client/api/application/create_application_api_v1_app_post.py", line 138, in sync
    return sync_detailed(
  File "/Users/alex.rejto/.pyenv/versions/aurelia/lib/python3.9/site-packages/svix/internal/openapi_client/api/application/create_application_api_v1_app_post.py", line 114, in sync_detailed
    return _parse_response(response=response)
  File "/Users/alex.rejto/.pyenv/versions/aurelia/lib/python3.9/site-packages/svix/internal/openapi_client/api/application/create_application_api_v1_app_post.py", line 56, in _parse_response
    raise HttpError(response.json(), response.status_code)
svix.internal.openapi_client.models.http_error.HttpError: {'code': 'conflict', 'detail': 'A conflict has occurred'}
```

I expect both of these calls to return safely.

### Version
Using latest svix pulled from docker-hub
pip Version: 0.57.1

**Comment by svix-dylan** [comment]
Looks like a silly oversight, we're taking a look! Thanks for bringing to our attention.

**Comment by svix-dylan** [comment]
@alexrejto We've fixed this issue, and the patch will ship to Docker Hub in the next hour, I'll followup here when it's available.

**Comment by svix-dylan** [comment]
@alexrejto Patched version has shipped to [Docker Hub](https://hub.docker.com/r/svix/svix-server)! Thanks again for bringing this to our attention.
